[package]
name = "crypto"
version = "0.1.0"
authors = ["lassemoldrup"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha2 = "0.9.3"
getrandom = "0.2.2"
rand_hc = "0.3.0"
rand = "0.8.3"
bitvec = "0.21.0"